Fusion Server: fusion_server::anonymous_namespace{json.cpp} Namespace Reference
fusion_server::anonymous_namespace{json.cpp} Namespace Reference
Functions
JSON MakeNotValidJSON () noexcept
JSON MakeTypeNotFound () noexcept
JSON MakeNotValidJoin () noexcept
JSON MakeNotValidUpdate () noexcept
JSON MakeNotValidLeave () noexcept
JSON MakeUnidentified () noexcept
Function Documentation
MakeNotValidJoin()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeNotValidJoin () noexcept
This method returns a JSON object contains an error message for the client informing that a "JOIN" package was ill-formed.
Returns
A JSON object contains an error message for the client informing that a "JOIN" package was ill-formed is returned.
Definition at line 47 of file json.cpp.
References MakeNotValidJoin().
Referenced by MakeNotValidJoin().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"A \"JOIN\" was ill-formed.."}}
     }, false, JSON::value_t::object);
 }
MakeNotValidJSON()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeNotValidJSON () noexcept
This method returns a JSON object contains an error message for the client informing about not valid JSON syntax.
Returns
A JSON object contains an error message for the client informing about not valid JSON syntax is returned.
Definition at line 15 of file json.cpp.
References MakeNotValidJSON().
Referenced by MakeNotValidJSON().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"One of the packages didn't contain a valid JSON."}}
     }, false, JSON::value_t::object);
 }
MakeNotValidLeave()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeNotValidLeave () noexcept
This method returns a JSON object contains an error message for the client informing that a "LEAVE" package was ill-formed.
Returns
A JSON object contains an error message for the client informing that a "LEAVE" package was ill-formed is returned.
Definition at line 79 of file json.cpp.
References MakeNotValidLeave().
Referenced by MakeNotValidLeave().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"A \"LEAVE\" was ill-formed."}}
     }, false, JSON::value_t::object);
 }
MakeNotValidUpdate()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeNotValidUpdate () noexcept
This method returns a JSON object contains an error message for the client informing that a "UPDATE" package was ill-formed.
Returns
A JSON object contains an error message for the client informing that a "UPDATE" package was ill-formed is returned.
Definition at line 63 of file json.cpp.
References MakeNotValidUpdate().
Referenced by MakeNotValidUpdate().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"A \"UPDATE\" was ill-formed."}}
     }, false, JSON::value_t::object);
 }
MakeTypeNotFound()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeTypeNotFound () noexcept
This method returns a JSON object contains an error message for the client informing that "type" field is not present is the received package.
Returns
A JSON object contains an error message for the client informing that "type" field is not present is the received package is returned.
Definition at line 31 of file json.cpp.
References MakeTypeNotFound().
Referenced by MakeTypeNotFound().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"One of the packages didn't have a \"type\" field."}}
     }, false, JSON::value_t::object);
 }
MakeUnidentified()
JSON fusion_server::anonymous_namespace{json.cpp}::MakeUnidentified () noexcept
This method returns a JSON object contains an error message for the client informing that a package was unidentified.
Returns
A JSON object contains an error message for the client informing that package was unidentified is returned.
Definition at line 95 of file json.cpp.
References MakeUnidentified().
Referenced by MakeUnidentified().
{
   return JSON({
     {"closed", {true}},
     {"type", {"error"}},
     {"message", {"Cannot identify a package."}}
     }, false, JSON::value_t::object);
 }