language: cpp
dist: bionic
sudo: true

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ppa:mhier/libboost-latest
          packages:
            - libboost1.67-dev
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - ppa:mhier/libboost-latest
          packages:
            - libboost1.67-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"


before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake -DFUSION_DOCS=OFF ..

script:
  - cmake --build . --target FusionServerTest --config Release -j 10
  - ./test/FusionServerTest