language: cpp
dist: bionic
sudo: true

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"


before_script:
  - sudo add-apt-repository ppa:mhier/libboost-latest
  - sudo apt-get update -y
  - sudo apt-get install -y libboost1.67-dev
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake -DFUSION_DOCS=OFF ..

script:
  - cmake --build . --target FusionServerTest --config Release -j 10
  - ./test/FusionServerTest