language: cpp
dist: bionic
sudo: false
os: linux

git:
  depth: 1

cache:
  apt: true

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - clang-8
      - liboost1.67-all-dev
      - cmake

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -DFUSION_DOCS=OFF ..

script:
  - cmake --build . --target FusionServerTest --config Release -j 10
  - ./test/FusionServerTest

after_failure:
  - cat ./.build/config.log