language: cpp
dist: bionic
sudo: true
os: linux

notifications:
  email: false

git:
  depth: 1

compiler:
  - clang
  - gcc

matrix:
  include:
    - env: COMPILER=g++
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
          - ppa:mhier/libboost-latest
        packages:
          - libboost1.67-dev
    - env: COMPILER=clang++
    compiler: clang
    addons:
      apt:
        update: true
        sources:
          - ppa:mhier/libboost-latest
        packages:
          - libboost1.67-dev

before_script:
  - export CXX=${COMPILER}
  - mkdir build
  - cd build
  - cmake -DFUSION_DOCS=OFF ..

script:
  - cmake --build . --target FusionServerTest --config Release -j 10
  - ./test/FusionServerTest