language: cpp

services:
  - docker

notifications:
  email: false

git:
  depth: 1
  quiet: true

before_install:
  - docker build -t nathiss/fusion_server_tests -f Dockerfile.travis .

script:
  - docker run nathiss/fusion_server_tests
