language: cpp
dist: bionic
sudo: false
os: linux

git:
  depth: 1

matrix:
  include:
    - env: COMPILER=clang++-8 BUILD=Release STANDARD=17
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - clang++-8
            - boost1.67
            - cmake
            - cmake-data


before_script:
  - if [[ "${TRAVIS_ON_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi

script:
  - mkdir build
  - cd build
  - cmake -DFUSION_DOCS=OFF ..
  - cmake --build . --target FusionServerTest --config Release -j 10
  - ./test/FusionServerTest