Fusion Server: fusion_server::WebSocketSession Class Reference
fusion_server::WebSocketSession Class Reference
#include <websocket_session.hpp>
Public Member Functions
WebSocketSession (const WebSocketSession &other)=delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
WebSocketSession (WebSocketSession &&other)=delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
WebSocketSession & operator= (const WebSocketSession &other)=delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
WebSocketSession & operator= (WebSocketSession &&other)=delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
WebSocketSession (boost::asio::ip::tcp::socket socket) noexcept
~WebSocketSession () noexcept
void Write (Package package) noexcept
template<typename Body , typename Allocator >
void Run (boost::beast::http::request< Body, boost::beast::http::basic_fields< Allocator >> request) noexcept
void Close () noexcept
void Close (Package package) noexcept
operator bool () const noexcept
const boost::asio::ip::tcp::socket::endpoint_type & GetRemoteEndpoint () const noexcept
Returns the remote endpoint. This method returns a reference to the remote endpoint connected to the stored socket.
void HandleHandshake (const boost::system::error_code &ec) noexcept
void HandleRead (const boost::system::error_code &ec, std::size_t bytes_transmitted) noexcept
void HandleWrite (const boost::system::error_code &ec, std::size_t bytes_transmitted) noexcept
Public Attributes
system_abstractions::IncommingPackageDelegate delegate_
Private Attributes
boost::beast::websocket::stream< boost::asio::ip::tcp::socket > websocket_
decltype(websocket_) ::next_layer_type::endpoint_type remote_endpoint_
The remote endpoint. This is the remote endpoint of the websocket_'s underlying socket.
boost::beast::multi_buffer buffer_
boost::asio::strand< boost::asio::io_context::executor_type > strand_
std::deque< Package > outgoing_queue_
std::mutex outgoing_queue_mtx_
std::atomic< bool > handshake_complete_
std::atomic< bool > in_closing_procedure_
PackageVerifier package_verifier_
std::shared_ptr< spdlog::logger > logger_
WebSocketSession's logger. This is a pointer to the logger used in WebSocketSession class.
Detailed Description
This class represents the WebSocket session between a client and the server.
Definition at line 25 of file websocket_session.hpp.
Constructor & Destructor Documentation
WebSocketSession() [1/3]
fusion_server::WebSocketSession::WebSocketSession (const WebSocketSession & other) delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
Parameters
[in] other Copied object.
WebSocketSession() [2/3]
fusion_server::WebSocketSession::WebSocketSession (WebSocketSession && other) delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
WebSocketSession() [3/3]
fusion_server::WebSocketSession::WebSocketSession (boost::asio::ip::tcp::socket socket) noexcept
This constructor takes the overship of the socket connected to a client and registers this session to the server.
Parameters
[in] socket The socket connected to a client.
Definition at line 19 of file websocket_session.cpp.
References fusion_server::Server::GetInstance(), and fusion_server::Server::Register().
     : websocket_{std::move(socket)},
       remote_endpoint_{websocket_.next_layer().remote_endpoint()},
       strand_{websocket_.get_executor()},
       handshake_complete_{false},
       in_closing_procedure_{false} {
   logger_ = spdlog::get("websocket");
   delegate_ = Server::GetInstance().Register(this);
 }
~WebSocketSession()
fusion_server::WebSocketSession::~WebSocketSession () noexcept
This destructor unregisters this session from the server.
Definition at line 29 of file websocket_session.cpp.
References fusion_server::Server::GetInstance(), and fusion_server::Server::Unregister().
{
   Server::GetInstance().Unregister(this);
 };
Member Function Documentation
Close() [1/2]
void fusion_server::WebSocketSession::Close () noexcept
This method allows the current writing to complete (if any) and then closes the connection. After its called no writing should be performed.
Note
This method is thread safe. It is indended to be called only once. If it is called more than once the behaviour is undefined.
Definition at line 72 of file websocket_session.cpp.
References in_closing_procedure_, logger_, outgoing_queue_, outgoing_queue_mtx_, and websocket_.
Referenced by Close(), HandleRead(), and HandleWrite().
{
   if (!in_closing_procedure_) {
     std::lock_guard l{outgoing_queue_mtx_};
     in_closing_procedure_ = true;
     if (outgoing_queue_.size() > 1) {
       // This means there are queued additional packages. We return and allow
       // HandleWrite to call this method after the writing has been completed.
       outgoing_queue_.erase(outgoing_queue_.begin() + 1, outgoing_queue_.end());
       return;
     }
     if (outgoing_queue_.size() == 1) {
       // This means there are no additional packages. We just returnand allow
       // HandleWrite to call this method after the writing has been completed.
       return;
     }
   }
   // If we're here it means either there are no packages queued or we are
   // already in closing procedure.
   boost::system::error_code ec;
   websocket_.close(boost::beast::websocket::close_code::none, ec);
     // Now callers should not performs writing to the WebSocket and should
     // perform reading as long as a read returns boost::beast::websocket::closed
     // error.
   if (ec) {
     logger_->warn("An error occured during closing a websocket. [Boost: {}]",
       ec.message());
     // TODO: Find out if the comment below applies to the WebSocket connections.
     // We do nothing, because
     // https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/basic_stream_socket/close/overload1.html
     // [Set on failure. Note that, even if the function indicates an error, the underlying descriptor is closed.]
   }
 }
Close() [2/2]
void fusion_server::WebSocketSession::Close (Package package) noexcept
This method performs a writing to the client and, when its completed, closes the connection. After its called no writing should be performed.
Parameters
[in] package The package to be send to the client.
Note
This method is thread safe. It is indended to be called only once. If it is called more than once the behaviour is undefined.
Definition at line 108 of file websocket_session.cpp.
References Close(), in_closing_procedure_, logger_, outgoing_queue_, outgoing_queue_mtx_, and websocket_.
{
   // We lock the mutex first, to ensure that no additional package will be
   // queued, after the closing procedure has started.
   std::lock_guard l{outgoing_queue_mtx_};
   in_closing_procedure_ = true;
   if (outgoing_queue_.size() > 1) {
     // This means we're already writing and other packages are waiting.
     // We remove all additional packages and queue the closing package.
     outgoing_queue_.erase(outgoing_queue_.begin() + 1, outgoing_queue_.end());
     outgoing_queue_.push_back(package);
     return;
   }
   if (outgoing_queue_.size() == 1) {
     // This means we're already writing and no packages are waiting.
     // We queue the closing package and return. HandleWrite method will perform
     // sending and closing.
     outgoing_queue_.push_back(package);
     return;
   }
   // If we're here it means no writing is performed right now.
   boost::system::error_code ec;
   websocket_.write(boost::asio::buffer(*package), ec);
   if (ec) {
     logger_->warn("An error occured during sync writing the closing message. [Boost:{}]",
       ec.message());
   }
   Close();
 }
GetRemoteEndpoint()
const boost::asio::ip::tcp::socket::endpoint_type & fusion_server::WebSocketSession::GetRemoteEndpoint () const noexcept
Returns the remote endpoint. This method returns a reference to the remote endpoint connected to the stored socket.
Returns
A reference to the remote endpoint connected to the stored socket is returned.
Note
This method is unsed for debugging and logging only.
Definition at line 144 of file websocket_session.cpp.
References remote_endpoint_.
Referenced by HandleHandshake(), HandleRead(), HandleWrite(), and Write().
{
   return remote_endpoint_;
 }
HandleHandshake()
void fusion_server::WebSocketSession::HandleHandshake (const boost::system::error_code & ec) noexcept
This method is the callback to asynchronous handshake with the client.
Parameters
[in] ec This is the Boost error code.
Definition at line 148 of file websocket_session.cpp.
References buffer_, GetRemoteEndpoint(), handshake_complete_, logger_, outgoing_queue_, outgoing_queue_mtx_, strand_, and websocket_.
{
   if (ec) {
     logger_->error("An error occured during handshake. Closing the session to {}. [Boost: {}]",
       GetRemoteEndpoint(), ec.message());
     return;
   }
   handshake_complete_ = true;
   logger_->debug("Handshake to {} completed.", GetRemoteEndpoint());
   if (std::lock_guard l{outgoing_queue_mtx_}; !outgoing_queue_.empty()) {
     logger_->debug("Sending a message queued before handshake complition.");
     websocket_.async_write(
       boost::asio::buffer(*outgoing_queue_.front()),
       boost::asio::bind_executor(
         strand_,
         [self = shared_from_this()](
           const boost::system::error_code& ec,
           std::size_t bytes_transmitted
         ) {
           self->HandleWrite(ec, bytes_transmitted);
         }
       )
     );
   }
   websocket_.async_read(
     buffer_,
     boost::asio::bind_executor(
       strand_,
       [self = shared_from_this()](
         const boost::system::error_code& ec,
         std::size_t bytes_transmitted
       ) {
         self->HandleRead(ec, bytes_transmitted);
       }
     )
   );
 }
HandleRead()
void fusion_server::WebSocketSession::HandleRead (const boost::system::error_code & ec, std::size_t bytes_transmitted) noexcept
This method is the callback to asynchronous read from the client.
Parameters
[in] ec This is the Boost error code.
[in] bytes_transmitted This is the amount of transmitted bytes.
Definition at line 188 of file websocket_session.cpp.
References buffer_, Close(), delegate_, GetRemoteEndpoint(), logger_, package_verifier_, strand_, fusion_server::PackageVerifier::Verify(), and websocket_.
{
   logger_->debug("Read {} bytes from {}.", bytes_transmitted, GetRemoteEndpoint());
   // TODO: find out what's that doing.
   boost::ignore_unused(buffer_);
   if (ec == boost::beast::websocket::error::closed) {
     logger_->debug("The session to {} was closed.", GetRemoteEndpoint());
     return;
   }
   if (ec == boost::asio::error::operation_aborted) {
     logger_->debug("The read operation from {} was abroted.", GetRemoteEndpoint());
     return;
   }
   if (ec) {
     logger_->error("An error occured during reading from {}. [Boost: {}]",
       GetRemoteEndpoint(), ec.message());
     // We assume what the session cannot be fixed.
     // TODO: Find out if that's true.
     return;
   }
   const auto package = boost::beast::buffers_to_string(buffer_.data());
   buffer_.consume(buffer_.size());
   auto [is_valid, msg] = package_verifier_.Verify(std::move(package));
   if (!is_valid) {
     logger_->warn("A package from {} was not valid. Closing the connection.",
       GetRemoteEndpoint());
     Close(system_abstractions::make_Package(msg.dump()));
     return;
   }
   boost::asio::post(websocket_.get_executor(), [this, msg = std::move(msg)]{
     delegate_(std::move(msg), this);
   });
   websocket_.async_read(
     buffer_,
     boost::asio::bind_executor(
       strand_,
       [self = shared_from_this()](
         const boost::system::error_code& ec,
         std::size_t bytes_transmitted
       ) {
         self->HandleRead(ec, bytes_transmitted);
       }
     )
   );
 }
HandleWrite()
void fusion_server::WebSocketSession::HandleWrite (const boost::system::error_code & ec, std::size_t bytes_transmitted) noexcept
This method is the callback to asynchronous write to the client.
Parameters
[in] ec This is the Boost error code.
[in] bytes_transmitted This is the amount of transmitted bytes.
Definition at line 242 of file websocket_session.cpp.
References Close(), GetRemoteEndpoint(), in_closing_procedure_, logger_, outgoing_queue_, outgoing_queue_mtx_, strand_, and websocket_.
{
   logger_->debug("Written {} bytes to {}.", bytes_transmitted,
     GetRemoteEndpoint());
   if (ec == boost::beast::websocket::error::closed) {
     logger_->debug("The session to {} was closed.", GetRemoteEndpoint());
     return;
   }
   if (ec) {
     logger_->error("An error occured during writing to {}. [Boost: {}]",
       GetRemoteEndpoint(), ec.message());
     return;
   }
   std::lock_guard l{outgoing_queue_mtx_};
   outgoing_queue_.pop_front();
   if (in_closing_procedure_) {
     // We're in closing procedure. The next package is the last one to be sent.
     // After writing we close the session.
     logger_->debug("[ClosingProcedure] Sync writing closing package to {}.",
       GetRemoteEndpoint());
     if (!outgoing_queue_.empty()) {
       boost::system::error_code ec;
       websocket_.write(boost::asio::buffer(*outgoing_queue_.front()), ec);
       if (ec) {
         logger_->error("An error occured during writing closing package to {}. [Boost: {}]",
           GetRemoteEndpoint(), ec.message());
       }
     }
     Close();
     return;
   }  // in_closing_procedure_
   if (!outgoing_queue_.empty()) {
     websocket_.async_write(
       boost::asio::buffer(*outgoing_queue_.front()),
       boost::asio::bind_executor(
         strand_,
         [self = shared_from_this()](
           const boost::system::error_code& ec,
           std::size_t bytes_transmitted
         ) {
           self->HandleWrite(ec, bytes_transmitted);
         }
       )
     );
   }
 }
operator bool()
fusion_server::WebSocketSession::operator bool () const explicit noexcept
This method returns a value that indicates whether or not the socket is connected to a client.
Returns
A value that indicates whether or not the socket is connected to a client is returned.
Definition at line 139 of file websocket_session.cpp.
References websocket_.
{
   return websocket_.is_open();
 }
operator=() [1/2]
WebSocketSession& fusion_server::WebSocketSession::operator= (const WebSocketSession & other) delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
Parameters
[in] other Copied object.
Returns
Reference to this object.
operator=() [2/2]
WebSocketSession& fusion_server::WebSocketSession::operator= (WebSocketSession && other) delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
Returns
Reference to this object.
Run()
template<typename Body , typename Allocator > void fusion_server::WebSocketSession::Run (boost::beast::http::request< Body, boost::beast::http::basic_fields< Allocator >> request) noexcept
This method upgrades the connection to the WebSocket Protocol and performs the asynchronous handshake.
Parameters
[in] request A HTTP Upgrade request.
Definition at line 252 of file websocket_session.hpp.
References strand_.
{
   websocket_.async_accept(
     std::move(request),
     boost::asio::bind_executor(
       strand_,
       [self = shared_from_this()](
         const boost::system::error_code& ec
       ) {
         self->HandleHandshake(ec);
       }
     )
   );
 }
Write()
void fusion_server::WebSocketSession::Write (Package package) noexcept
This method delegates the write operation to the client. Since Boost::Beast allows only one writing at a time, the packages is always queued and if no writing is taking place the asynchronous write operation is called.
Parameters
[in] package The package to be send to the client. The shared_ptr is used to ensure that the package will be freed only if it has been sent to all the specific clients.
Note
This method is thread-safe.
Definition at line 33 of file websocket_session.cpp.
References GetRemoteEndpoint(), handshake_complete_, in_closing_procedure_, logger_, outgoing_queue_, outgoing_queue_mtx_, strand_, and websocket_.
{
   std::lock_guard l{outgoing_queue_mtx_};
   if (in_closing_procedure_) {
     logger_->warn("Trying to write to {} while in closing procedue. Aborting the task",
       GetRemoteEndpoint());
     // We're not allowed to queued any package, when the closing procedure has
     // started.
     return;
   }
   outgoing_queue_.push_back(package);
   if (outgoing_queue_.size() > 1) {
     // Means we're already writing.
     return;
   }
   if (!handshake_complete_) {
     logger_->warn("Trying to write to {} before handshake was complete. Aborting the task",
       GetRemoteEndpoint());
     // We need to wait for the handshake to complete.
     return;
   }
   websocket_.async_write(
       boost::asio::buffer(*outgoing_queue_.front()),
       boost::asio::bind_executor(
         strand_,
         [self = shared_from_this()](
           const boost::system::error_code& ec,
           std::size_t bytes_transmitted
         ) {
           self->HandleWrite(ec, bytes_transmitted);
         }
       )
   );
 }
Member Data Documentation
buffer_
boost::beast::multi_buffer fusion_server::WebSocketSession::buffer_ private
This is the buffer for the incomming packages.
Definition at line 210 of file websocket_session.hpp.
Referenced by HandleHandshake(), and HandleRead().
delegate_
system_abstractions::IncommingPackageDelegate fusion_server::WebSocketSession::delegate_
This delegate is called each time when a new package arrives.
Definition at line 192 of file websocket_session.hpp.
Referenced by HandleRead().
handshake_complete_
std::atomic<bool> fusion_server::WebSocketSession::handshake_complete_ private
This indicates whether or not the handshake has been completed.
Definition at line 230 of file websocket_session.hpp.
Referenced by HandleHandshake(), and Write().
in_closing_procedure_
std::atomic<bool> fusion_server::WebSocketSession::in_closing_procedure_ private
This indicates wheter or not the closing procedure has started. If it's true, no writing to the
Definition at line 236 of file websocket_session.hpp.
Referenced by Close(), HandleWrite(), and Write().
outgoing_queue_
std::deque<Package> fusion_server::WebSocketSession::outgoing_queue_ private
This queue holds all outgoing packages, which have not yet been sent.
Definition at line 220 of file websocket_session.hpp.
Referenced by Close(), HandleHandshake(), HandleWrite(), and Write().
outgoing_queue_mtx_
std::mutex fusion_server::WebSocketSession::outgoing_queue_mtx_ private
This is the mutex for outgoing queue.
Definition at line 225 of file websocket_session.hpp.
Referenced by Close(), HandleHandshake(), HandleWrite(), and Write().
package_verifier_
PackageVerifier fusion_server::WebSocketSession::package_verifier_ private
This is a package verifier used to parse a read package and verify if it's properly formed.
Definition at line 242 of file websocket_session.hpp.
Referenced by HandleRead().
strand_
boost::asio::strand<boost::asio::io_context::executor_type> fusion_server::WebSocketSession::strand_ private
This is the strand for this instance of WebSocketSession class.
Definition at line 215 of file websocket_session.hpp.
Referenced by HandleHandshake(), HandleRead(), HandleWrite(), Run(), and Write().
websocket_
boost::beast::websocket::stream<boost::asio::ip::tcp::socket> fusion_server::WebSocketSession::websocket_ private
This is the WebSocket wrapper around the socket connected to a client.
Definition at line 199 of file websocket_session.hpp.
Referenced by Close(), HandleHandshake(), HandleRead(), HandleWrite(), operator bool(), and Write().
The documentation for this class was generated from the following files:
include/fusion_server/websocket_session.hpp
src/websocket_session.cpp