Fusion Server: fusion_server::HTTPSession Class Reference
fusion_server::HTTPSession Class Reference
#include <http_session.hpp>
Public Types
using Request_t = boost::beast::http::request< boost::beast::http::string_body >
using Response_t = boost::beast::http::response< boost::beast::http::string_body >
Public Member Functions
HTTPSession (const HTTPSession &other)=delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
HTTPSession (HTTPSession &&other)=delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
HTTPSession & operator= (const HTTPSession &other)=delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
HTTPSession & operator= (HTTPSession &&other)=delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
HTTPSession (boost::asio::ip::tcp::socket socket) noexcept
A socket connected to a client. If the socket is not connected or is not in "ready" state, the behaviour is undefined.
~HTTPSession () noexcept
void Run () noexcept
void Close () noexcept
operator bool () const noexcept
void HandleRead (const boost::system::error_code &ec, std::size_t bytes_transmitted) noexcept
void HandleWrite (const boost::system::error_code &ec, std::size_t bytes_transmitted, bool close) noexcept
Private Member Functions
void PerformAsyncWrite (Response_t response) noexcept
Response_t MakeResponse () const noexcept
Constructs a response to the stored request. This method returns a HTTP response to the stored HTTP request.
Response_t MakeBadRequest () const noexcept
Constructs a "Bad Request" (400) response. This method returns a HTTP response with the status code set to 400.
Private Attributes
boost::asio::ip::tcp::socket socket_
boost::asio::strand< boost::asio::io_context::executor_type > strand_
boost::beast::flat_buffer buffer_
boost::beast::http::request< boost::beast::http::string_body > request_
Detailed Description
This class represents the HTTP session between a client and the server.
Member Typedef Documentation
Request_t
using fusion_server::HTTPSession::Request_t = boost::beast::http::request<boost::beast::http::string_body>
This is the type of a HTTP request used in this class.
Response_t
using fusion_server::HTTPSession::Response_t = boost::beast::http::response<boost::beast::http::string_body>
This is the type of a HTTP response used in this class.
Constructor & Destructor Documentation
HTTPSession() [1/3]
fusion_server::HTTPSession::HTTPSession (const HTTPSession & other) delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
Parameters
[in] other Copied object.
HTTPSession() [2/3]
fusion_server::HTTPSession::HTTPSession (HTTPSession && other) delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
HTTPSession() [3/3]
fusion_server::HTTPSession::HTTPSession (boost::asio::ip::tcp::socket socket) noexcept
A socket connected to a client. If the socket is not connected or is not in "ready" state, the behaviour is undefined.
This constructor takes the overship of the socket connected to a client.
Parameters
[in] socket
References ~HTTPSession().
     : socket_{std::move(socket)}, strand_{socket_.get_executor()} {
 }
~HTTPSession()
fusion_server::HTTPSession::~HTTPSession () default noexcept
This is the default destructor.
Referenced by HTTPSession().
Member Function Documentation
Close()
void fusion_server::HTTPSession::Close () noexcept
This method closes the connection immediately. Any asynchronous operation will be cancelled.
References socket_.
{
 #ifdef DEBUG
   std::cout << "[HTTPSession: " << this << "] Closing" << std::endl;
 #endif
   try {
     socket_.close();
   }
   catch (const boost::system::system_error& e) {
     std::cerr << "HTTPSession::Close: " << e.what() << std::endl;
     // We do nothing, because
     // https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/basic_stream_socket/close/overload1.html
     // [Thrown on failure. Note that, even if the function indicates an error, the underlying descriptor is closed.]
   }
 }
HandleRead()
void fusion_server::HTTPSession::HandleRead (const boost::system::error_code & ec, std::size_t bytes_transmitted) noexcept
This method is the callback to asynchronous reading from the client. After parsing the request it performs asynchronous responding.
Parameters
[in] ec This is the Boost error code.
[in] bytes_transmitted This is the amount of transmitted bytes.
References MakeBadRequest(), MakeResponse(), PerformAsyncWrite(), request_, Run(), and socket_.
{
 #ifdef DEBUG
   std::cout << "[HTTPSession: " << this << "] Read " << bytes_transmitted << " bytes." << std::endl;
 #endif
   if (ec == boost::beast::http::error::end_of_stream ||
     ec == boost::beast::http::error::partial_message) {
     // The client closed the connection. We either read none or read incomplete
     // message. We don't care about both.
     socket_.shutdown(boost::asio::ip::tcp::socket::shutdown_send);
     return;
   }
   if (ec == boost::beast::http::error::buffer_overflow ||
     ec == boost::beast::http::error::header_limit ||
     ec == boost::beast::http::error::body_limit) {
     // This means a HTTP content would exceed the maximum size of the buffer.
     // This should never happened in normal use, so we close the connection.
     std::cerr << "[HTTPSession: " << this << "] message from " << socket_.remote_endpoint()
       << " is too large. Closing the connection." << std::endl;
     socket_.shutdown(boost::asio::ip::tcp::socket::shutdown_both);
     return;
   }
   if (ec == boost::beast::http::error::bad_line_ending ||
     ec == boost::beast::http::error::bad_method ||
     ec == boost::beast::http::error::bad_target ||
     ec == boost::beast::http::error::bad_version ||
     ec == boost::beast::http::error::bad_status ||
     ec == boost::beast::http::error::bad_reason ||
     ec == boost::beast::http::error::bad_field ||
     ec == boost::beast::http::error::bad_value ||
     ec == boost::beast::http::error::bad_content_length ||
     ec == boost::beast::http::error::bad_transfer_encoding ||
     ec == boost::beast::http::error::bad_chunk ||
     ec == boost::beast::http::error::bad_chunk_extension ||
     ec == boost::beast::http::error::bad_obs_fold) {
     // This means the request is ill-formed.
     PerformAsyncWrite(MakeBadRequest());
     }
   if (ec) {
     std::cerr << "HTTPSession::HandleRead: " << ec.message() << std::endl;
     return;
   }
   if (boost::beast::websocket::is_upgrade(request_)) {
 #ifdef DEBUG
     std::cout << "[HTTPSession: " << this << "] Received an upgrade request." << std::endl;
 #endif
     std::make_shared<WebSocketSession>(std::move(socket_))->Run(
       std::move(request_)
     );
     return;
   }
   PerformAsyncWrite(MakeResponse());
 }
HandleWrite()
void fusion_server::HTTPSession::HandleWrite (const boost::system::error_code & ec, std::size_t bytes_transmitted, bool close) noexcept
This method is the callback to asynchronous writing to the client. After checking if an error occured it performs asynchronous reading from the client.
Parameters
[in] ec This is the Boost error code.
[in] bytes_transmitted This is the amount of transmitted bytes.
[in] close This indicates whether or not we should close the connection. The response indicated the "Connection: close" semantic.
References buffer_, request_, and socket_.
{
 #ifdef DEBUG
   std::cout << "[HTTPSession: " << this << "] Written " << bytes_transmitted << " bytes." << std::endl;
 #endif
   if (ec) {
     std::cerr << "HTTPSession::HandleWrite: " << ec.message() << std::endl;
     return;
   }
   if (close) {
     // The client closed its connection. We do the same.
     socket_.shutdown(boost::asio::ip::tcp::socket::shutdown_send);
     return;
   }
   // Clear contents of the request message, otherwise the read behavior is undefined.
   request_ = {};
   boost::beast::http::async_read(
     socket_,
     buffer_,
     request_,
     [self = shared_from_this()](
       const boost::system::error_code& ec,
       std::size_t bytes_transmitted
     ) {
       self->HandleRead(ec, bytes_transmitted);
     }
   );
 }
MakeBadRequest()
auto fusion_server::HTTPSession::MakeBadRequest () const private noexcept
Constructs a "Bad Request" (400) response. This method returns a HTTP response with the status code set to 400.
Returns
A HTTP "Bad Request" (400) response.
See also
[RFC 2616] 10.4.1 400 Bad Request
References request_.
Referenced by HandleRead().
{
   Response_t res{
     boost::beast::http::status::bad_request,
     request_.version()
   };
   res.set(boost::beast::http::field::server, BOOST_BEAST_VERSION_STRING);
   res.set(boost::beast::http::field::content_type, "text/html; charset=utf-8");
   res.keep_alive(request_.keep_alive());
   res.body() = "<html><body><h1>400 Bad Request</h1></body></html>";
   res.prepare_payload();
   return res;
 }
MakeResponse()
auto fusion_server::HTTPSession::MakeResponse () const private noexcept
Constructs a response to the stored request. This method returns a HTTP response to the stored HTTP request.
Returns
A HTTP response to the stored request.
References request_.
Referenced by HandleRead().
{
   Response_t res{
     request_.target() == "/" ? boost::beast::http::status::ok :
     boost::beast::http::status::not_found, request_.version()
   };
   res.set(boost::beast::http::field::server, BOOST_BEAST_VERSION_STRING);
   res.set(boost::beast::http::field::content_type, "text/plain; charset=utf-8");
   res.keep_alive(request_.keep_alive());
   res.body() = "FeelsBadMan\r\n";
   res.prepare_payload();
   return res;
 }
operator bool()
fusion_server::HTTPSession::operator bool () const explicit noexcept
This method returns a value that indicates whether or not the socket is connected to a client.
Returns
A value that indicates whether or not the socket is connected to a client is returned.
References socket_.
{
   return socket_.is_open();
 }
operator=() [1/2]
HTTPSession& fusion_server::HTTPSession::operator= (const HTTPSession & other) delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
Parameters
[in] other Copied object.
Returns
Reference to this object.
operator=() [2/2]
HTTPSession& fusion_server::HTTPSession::operator= (HTTPSession && other) delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
Returns
Reference to this object.
PerformAsyncWrite()
void fusion_server::HTTPSession::PerformAsyncWrite (Response_t response) private noexcept
This method calls asynchronous writing to the client.
Parameters
[in] response A HTTP response to be sent.
Note
This method has to take the ownership of the response object.
References socket_.
Referenced by HandleRead().
{
   auto response_ptr = std::make_shared<decltype(response)>(std::move(response));
   boost::beast::http::async_write(
     socket_,
     *response_ptr,
     [self = shared_from_this(), response_ptr](
       const boost::system::error_code& ec,
       std::size_t bytes_transmitted
     ) {
       self->HandleWrite(ec, bytes_transmitted, response_ptr->need_eof());
     }
   );
 }
Run()
void fusion_server::HTTPSession::Run () noexcept
This method starts the loop of asynchronous reads. It is indended to be called only once. If it is called more than once the behaviour is undefined.
References buffer_, request_, and socket_.
Referenced by HandleRead().
{
   boost::beast::http::async_read(
     socket_,
     buffer_,
     request_,
     [self = shared_from_this()](
       const boost::system::error_code& ec,
       std::size_t bytes_transmitted
     ) {
       self->HandleRead(ec, bytes_transmitted);
     }
   );
 }
Member Data Documentation
buffer_
boost::beast::flat_buffer fusion_server::HTTPSession::buffer_ private
This is the buffer used to store the client's requests.
Referenced by HandleWrite(), and Run().
request_
boost::beast::http::request<boost::beast::http::string_body> fusion_server::HTTPSession::request_ private
This holds the parsed client's request.
Referenced by HandleRead(), HandleWrite(), MakeBadRequest(), MakeResponse(), and Run().
socket_
boost::asio::ip::tcp::socket fusion_server::HTTPSession::socket_ private
This is the socket connected to the client.
Referenced by Close(), HandleRead(), HandleWrite(), operator bool(), PerformAsyncWrite(), and Run().
strand_
boost::asio::strand<boost::asio::io_context::executor_type> fusion_server::HTTPSession::strand_ private
This is the strand for this instance of the HTTPSession class.
The documentation for this class was generated from the following files:
include/fusion_server/http_session.hpp
src/http_session.cpp