Fusion Server: fusion_server::Listener Class Reference
fusion_server::Listener Class Reference
#include <listener.hpp>
Public Member Functions
Listener (const Listener &other)=delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
Listener (Listener &&other)=delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Listener & operator= (const Listener &other)=delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
Listener & operator= (Listener &&other)=delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Listener (boost::asio::io_context &ioc, std::string_view ip_address, std::uint16_t port_numer) noexcept
Listener (boost::asio::io_context &ioc, boost::asio::ip::tcp::endpoint endpoint) noexcept
Listener (boost::asio::io_context &ioc, std::uint16_t port_number) noexcept
~Listener () noexcept
void Run () noexcept
void HandleAccept (const boost::system::error_code &) noexcept
Private Member Functions
void OpenAcceptor () noexcept
Private Attributes
boost::asio::io_context & ioc_
boost::asio::ip::tcp::acceptor acceptor_
boost::asio::ip::tcp::socket socket_
boost::asio::ip::tcp::endpoint endpoint_
Detailed Description
This class represends the local endpoint used to accept new connections from the clients.
Constructor & Destructor Documentation
Listener() [1/5]
fusion_server::Listener::Listener (const Listener & other) delete
Explicitly deleted copy constructor. It's deleted due to presence of boost::asio's socket.
Parameters
[in] other Copied object.
Listener() [2/5]
fusion_server::Listener::Listener (Listener && other) delete
Explitly deleted move constructor. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
Listener() [3/5]
fusion_server::Listener::Listener (boost::asio::io_context & ioc, std::string_view ip_address, std::uint16_t port_numer) noexcept
This constructor may be used for accepting connections on a specific local interace.
Parameters
[in] ioc The context for providing core I/O functionality.
[in] ip_address The ip address of a local interface.
[in] port_numer A port numer.
     : ioc_{ioc}, acceptor_{ioc_}, socket_{ioc_},
       endpoint_{boost::asio::ip::make_address(ip_address), port_numer} {
   OpenAcceptor();
 }
Listener() [4/5]
fusion_server::Listener::Listener (boost::asio::io_context & ioc, boost::asio::ip::tcp::endpoint endpoint) noexcept
This constructor may be used for accepting connections on the given endpoint.
Parameters
[in] ioc The context for providing core I/O functionality.
[in] endpoint A local endpoint.
     : ioc_{ioc}, acceptor_{ioc_}, socket_{ioc_},
       endpoint_{std::move(endpoint)} {
   OpenAcceptor();
 }
Listener() [5/5]
fusion_server::Listener::Listener (boost::asio::io_context & ioc, std::uint16_t port_number) noexcept
This constructor may be used for accepting connection on any local interface.
Parameters
[in] ioc The context for providing core I/O functionality.
[in] port_number A port numer.
References ~Listener().
     : ioc_{ioc}, acceptor_{ioc_}, socket_{ioc_},
       endpoint_{boost::asio::ip::tcp::v4(), port_number} {
   OpenAcceptor();
 }
~Listener()
fusion_server::Listener::~Listener () default noexcept
This is the default destructor.
Referenced by Listener().
Member Function Documentation
HandleAccept()
void fusion_server::Listener::HandleAccept (const boost::system::error_code & ec) noexcept
This is the callback to asynchronous accept of a new connection.
References acceptor_, Run(), and socket_.
{
   if (ec) {
     std::cerr << "Listener::HandleAccept: " << ec.message() << std::endl;
     // TODO: find out if any error can cause the listener to stop working.
   }
   else {
 #ifdef DEBUG
     std::cout << "[Listener: " << this << "] New connection from " << socket_.remote_endpoint() << std::endl;
 #endif
     std::make_shared<HTTPSession>(std::move(socket_))->Run();
   }
   acceptor_.async_accept(
     socket_,
     [self = shared_from_this()](const boost::system::error_code& ec) {
       self->HandleAccept(ec);
     }
   );
 }
OpenAcceptor()
void fusion_server::Listener::OpenAcceptor () private noexcept
This method opens the acceptor & binds it to the endpoint.
References acceptor_, and endpoint_.
{
   boost::system::error_code ec;
   acceptor_.open(endpoint_.protocol(), ec);
   if (ec) {
     std::cerr << "Listener::OpenAcceptor" << ec.message() << std::endl;
     return;
   }
   acceptor_.set_option(boost::asio::socket_base::reuse_address(true), ec);
   if (ec) {
     std::cerr << "Listener::OpenAcceptor" << ec.message() << std::endl;
     return;
   }
   acceptor_.bind(endpoint_, ec);
   if (ec) {
     std::cerr << "Listener::OpenAcceptor" << ec.message() << std::endl;
     return;
   }
   acceptor_.listen(boost::asio::socket_base::max_listen_connections, ec);
   if (ec) {
     std::cerr << "Listener::OpenAcceptor" << ec.message() << std::endl;
     return;
   }
 #ifdef DEBUG
   std::cout << "Listening on " << endpoint_ << std::endl;
 #endif
 }
operator=() [1/2]
Listener& fusion_server::Listener::operator= (const Listener & other) delete
Explicitly deleted copy operator. It's deleted due to presence of socket in class hierarchy.
Parameters
[in] other Copied object.
Returns
Reference to this object.
operator=() [2/2]
Listener& fusion_server::Listener::operator= (Listener && other) delete
Explitly deleted move operator. It's deleted just because it's not used. Although it could be dangerous, due to asynchronous operations are made on this object.
Parameters
[in] other Moved object.
Returns
Reference to this object.
Run()
void fusion_server::Listener::Run () noexcept
This method starts the asynchronous accepting loop on the specified endpoint.
References acceptor_, and socket_.
Referenced by HandleAccept().
{
 #ifdef DEBUG
   std::cout << "Starting asynchronous accepting." << std::endl;
 #endif
   acceptor_.async_accept(
     socket_,
     [self = shared_from_this()](const boost::system::error_code& ec) {
       self->HandleAccept(ec);
     }
   );
 }
Member Data Documentation
acceptor_
boost::asio::ip::tcp::acceptor fusion_server::Listener::acceptor_ private
This is the acceptor for accepting new connections.
Referenced by HandleAccept(), OpenAcceptor(), and Run().
endpoint_
boost::asio::ip::tcp::endpoint fusion_server::Listener::endpoint_ private
This is the local endpoint on which new connections will be accepted.
Referenced by OpenAcceptor().
ioc_
boost::asio::io_context& fusion_server::Listener::ioc_ private
The context for providing core I/O functionality.
socket_
boost::asio::ip::tcp::socket fusion_server::Listener::socket_ private
This is the socket used to handle a new incomming connection.
Referenced by HandleAccept(), and Run().
The documentation for this class was generated from the following files:
include/fusion_server/listener.hpp
src/listener.cpp