Fusion Server: fusion_server::Game Class Reference
fusion_server::Game Class Reference
#include <game.hpp>
Public Types
enum Team { Team::kFirst, Team::kSecond, Team::kRandom }
using join_result_t = std::optional< std::tuple< system_abstractions::IncommingPackageDelegate &, JSON, std::size_t > >
Public Member Functions
Game (const Game &other) noexcept=delete
Explicitly deleted copy constructor. It's deleted due to presence of unique_ptr in class hierarchy.
Game & operator= (const Game &other) noexcept=delete
Explicitly deleted copy operator. It's deleted due to presence of unique_ptr in class hierarchy.
Game (const std::string &game_name) noexcept
join_result_t Join (WebSocketSession *session, Team team=Team::kRandom) noexcept
bool Leave (WebSocketSession *session) noexcept
void BroadcastPackage (const std::shared_ptr< Package > &package) noexcept
std::size_t GetPlayersCount () const noexcept
Static Public Attributes
static constexpr size_t kMaxPlayersPerTeam = 5
Private Member Functions
bool IsInGame (WebSocketSession *session) const noexcept
JSON GetCurrentState () const noexcept
void DoResponse (WebSocketSession *session, const JSON &request) noexcept
Private Attributes
std::set< std::pair< WebSocketSession *, std::unique_ptr< Player > > > first_team_
std::mutex first_team_mtx_
std::set< std::pair< WebSocketSession *, std::unique_ptr< Player > > > second_team_
std::mutex second_team_mtx_
std::map< WebSocketSession *, Team > players_cache_
Players' team cache. This maps the WebSocket session to the team identifier in which the player currently is.
std::mutex players_cache_mtx_
std::atomic< std::size_t > next_player_id_
std::map< std::variant< Ray *, Player * >, Ray > rays_
std::mutex rays_mtx_
system_abstractions::IncommingPackageDelegate delegate_
std::shared_ptr< spdlog::logger > logger_
Game's logger. This is a pointer to the logger used in Game class.
Detailed Description
This class represents a game. It creates a common context for all joined clients.
Definition at line 44 of file game.hpp.
Member Typedef Documentation
join_result_t
using fusion_server::Game::join_result_t = std::optional<std::tuple<system_abstractions::IncommingPackageDelegate&, JSON, std::size_t> >
This is the return type of the Join method.
Definition at line 70 of file game.hpp.
Member Enumeration Documentation
Team
enum fusion_server::Game::Team strong
This enum contains the teams' identifiers.
Enumerator
kFirst
This identifies the first team in the game.
kSecond
This identifies the second team in the game.
kRandom
This indicates that a WebSocketSession should be assigned to a random team.
Definition at line 49 of file game.hpp.
                   {
     kFirst,
     kSecond,
     kRandom,
   };
Constructor & Destructor Documentation
Game() [1/2]
fusion_server::Game::Game (const Game & other) delete noexcept
Explicitly deleted copy constructor. It's deleted due to presence of unique_ptr in class hierarchy.
Parameters
[in] other Copied object.
Game() [2/2]
fusion_server::Game::Game (const std::string & game_name) explicit noexcept
This constructor creates the asynchronous reading delegate and creates a new logger for this game.
Parameters
[in] game_name The name of this game.
Definition at line 21 of file game.cpp.
     : next_player_id_{0} {
   std::string logger_name{"game["};
   logger_name += game_name;
   logger_name += "]";
   logger_ = system_abstractions::CreateLogger(std::move(logger_name), false);
   delegate_ = [this](const JSON& package, WebSocketSession* src){
     DoResponse(src, package);
   };
 }
Member Function Documentation
BroadcastPackage()
void fusion_server::Game::BroadcastPackage (const std::shared_ptr< Package > & package) noexcept
This method broadcasts the given package to all clients connected to this game.
Parameters
[in] package The package to be broadcasted.
Definition at line 130 of file game.cpp.
Referenced by DoResponse().
{
   {
     std::lock_guard l{first_team_mtx_};
     for (auto& pair : first_team_) {
       pair.first->Write(package);
     }
   }
   {
     std::lock_guard l{second_team_mtx_};
     for (const auto& pair : second_team_) {
       pair.first->Write(package);
     }
   }
 }
DoResponse()
void fusion_server::Game::DoResponse (WebSocketSession * session, const JSON & request) private noexcept
This method prepairs a response for the given request and either sends it or broadcasts it.
Parameters
[in] session The WebSocket session connected to the client.
[in] request This is a client's request.
Definition at line 198 of file game.cpp.
References BroadcastPackage(), first_team_, first_team_mtx_, GetCurrentState(), fusion_server::Server::GetInstance(), Leave(), logger_, fusion_server::Server::Register(), second_team_, and second_team_mtx_.
{
   const auto make_unidentified = [] {
     return JSON({
       {"type", {"warning"}},
       {"message", {"Received an unidentified package."}},
       {"closed", {false}},
     }, false, JSON::value_t::object);
   };
   // analysing
   if (request["type"] == "update") {
     if (request["team_id"] == 0) {
       std::lock_guard l{first_team_mtx_};
       for (const auto& [ws, player_ptr] : first_team_) {
         if (ws == session) {
           player_ptr->angle_ = request["angle"];
           player_ptr->position_.x = request["position"];
         }
       }
     } else {
       std::lock_guard l{second_team_mtx_};
       for (const auto& [ws, player_ptr] : second_team_) {
         if (ws == session) {
           player_ptr->angle_ = request["angle"];
           player_ptr->position_.x = request["position"];
         }
       }
     }
     auto response = [this] {
       JSON ret = JSON::object();
       auto state = GetCurrentState();
       return JSON({
         {"type", {"update"}},
         {"players", {state["players"]}},
         {"rays", {state["rays"]}},
       }, false, JSON::value_t::object);
     }();
     BroadcastPackage(std::make_shared<Package>(std::move(response)));
   }  // "update"
   if (request["type"] == "leave") {
     if (!Leave(session)) {
       logger_->warn("Trying to remove an unjoined session ({}).",
         session->GetRemoteEndpoint());
       session->Close();
       return;
     }
     logger_->debug("Session {} left the game.", session->GetRemoteEndpoint());
     // TODO(nathiss): broadcast the leaving
     session->delegate_ = Server::GetInstance().Register(session);
   }
   logger_->warn("Received an unidentified package from {}. [type={}]",
     session->GetRemoteEndpoint(), request["type"].dump());
   session->Write(std::make_shared<Package>(make_unidentified()));
 }
GetCurrentState()
JSON fusion_server::Game::GetCurrentState () const private noexcept
This method returns a JSON object containg an encoded current state of this game.
Returns
A JSON object containg an encoded current state of this game is returned.
Definition at line 165 of file game.cpp.
References first_team_, first_team_mtx_, rays_, rays_mtx_, second_team_, and second_team_mtx_.
Referenced by DoResponse().
{
   auto state = [] {
     return JSON({
       {"players", {JSON::array()}},
       {"rays", {JSON::array()}},
     }, false, JSON::value_t::object);
   }();
   {
     std::lock_guard l{rays_mtx_};
     for (auto& [_, ray] : rays_) {
       state["rays"].push_back(ray.ToJson());
     }
   }
   {
     std::lock_guard l{first_team_mtx_};
     for (auto& [_, player_ptr] : first_team_) {
       state["players"].push_back(player_ptr->ToJson());
     }
   }
   {
     std::lock_guard l{second_team_mtx_};
     for (auto& [_, player_ptr] : second_team_) {
       state["players"].push_back(player_ptr->ToJson());
     }
   }
   return state;
 }
GetPlayersCount()
std::size_t fusion_server::Game::GetPlayersCount () const noexcept
This method returns the amount of players in this game.
Returns
The amount of players in this game is returned.
Definition at line 146 of file game.cpp.
References first_team_, first_team_mtx_, second_team_, and second_team_mtx_.
{
   std::size_t ret{0};
   {
     std::lock_guard l{first_team_mtx_};
     ret += first_team_.size();
   }
     {
     std::lock_guard l{second_team_mtx_};
     ret += second_team_.size();
   }
   return ret;
 }
IsInGame()
bool fusion_server::Game::IsInGame (WebSocketSession * session) const private noexcept
This method returns an indication whether or not the client identified by the given session has already joined to this game.
Parameters
[in] session The WebSocketSession connected to the client.
Returns
An indication whether or not the client identified by the given session has already joined to this game is returned.
Definition at line 159 of file game.cpp.
References players_cache_, and players_cache_mtx_.
{
   std::lock_guard l{players_cache_mtx_};
   return players_cache_.count(session) != 0;
 }
Join()
Game::join_result_t fusion_server::Game::Join (WebSocketSession * session, Team team = Team::kRandom) noexcept
This method joins the client to this game and adds its session to the proper team. If the joining was successful it returns a pair of a new incomming package delegate and a JSON object containing information about the current state of the game, otherwise the returned object is in its invalid state.
Parameters
[in] session This is the WebSocket session connected to a client.
[in] team This identifies the team, to which the client will be assigned. The default value indicates that the client will be assigned to a random team.
Returns
If the joining was successful pair of a new incomming package delegate and a JSON object containing information about the current state of the game is returned, otherwise the returned object is in its invalid state.
Note
If a client has already joined to this game, the method does nothing and returns an invalid state object.
Definition at line 33 of file game.cpp.
{
   if (IsInGame(session)) {
     logger_->warn("Tryig to join already joined session. ({})",
       session->GetRemoteEndpoint());
     return {};
   }
   std::size_t player_id;
   switch (team) {
     case Team::kFirst: {
       {
         std::lock_guard l{first_team_mtx_};
         if (first_team_.size() >= kMaxPlayersPerTeam) {
           return {};
         }
         player_id = next_player_id_++;
         first_team_.insert({session, std::make_unique<Player>(player_id)});
       }
       break;
     }
     case Team::kSecond: {
       {
         std::lock_guard l{second_team_mtx_};
         if (second_team_.size() >= kMaxPlayersPerTeam) {
           return {};
         }
         player_id = next_player_id_++;
         second_team_.insert({session, std::make_unique<Player>(player_id)});
       }
       break;
     }
     case Team::kRandom:
     default: {
       std::lock_guard lf{first_team_mtx_};
       if (std::lock_guard ls{second_team_mtx_}; first_team_.size() >= second_team_.size()) {
         if (second_team_.size() >= kMaxPlayersPerTeam) {
           return {};
         }
         player_id = next_player_id_++;
         team = Team::kSecond;
         second_team_.insert({session, std::make_unique<Player>(player_id)});
         break;
       }
       // The second team is bigger than the first.
       if (first_team_.size() >= kMaxPlayersPerTeam) {
         return {};
       }
       player_id = next_player_id_++;
       team = Team::kFirst;
       first_team_.insert({session, std::make_unique<Player>(player_id)});
     }
   }  // switch
   logger_->debug("{} joined the game.", session->GetRemoteEndpoint());
   {
     std::lock_guard l{players_cache_mtx_};
     players_cache_[session] = team;
   }
   return std::make_optional<join_result_t::value_type>(delegate_, GetCurrentState(), player_id);
 }
Leave()
bool fusion_server::Game::Leave (WebSocketSession * session) noexcept
This method removes the given session from this game. It returns a indication whether or not the session has been removed.
Parameters
[in] session The session to be removed from this game.
Returns
A indication whether or not the session has been removed is returned.
Note
If the session has not been assigned to this game, the method does nothing.
Definition at line 97 of file game.cpp.
Referenced by DoResponse().
{
   Team team_id{Team::kRandom};
   if (std::lock_guard l{players_cache_mtx_}; players_cache_.count(session) != 0) {
     team_id = players_cache_[session];
     players_cache_.erase(session);
   } else {
     logger_->warn("The given session doesn't exist in the cache. Searching in both teams.");
   }
   if (team_id == Team::kFirst || team_id == Team::kRandom) {
     std::lock_guard l{first_team_mtx_};
     for (const auto& pair : first_team_) {
       if (session == pair.first) {
         first_team_.erase(pair);
         return true;
       }
     }
   }
   if (team_id == Team::kSecond || team_id == Team::kRandom) {
     std::lock_guard l{second_team_mtx_};
     for (const auto& pair : second_team_) {
       if (session == pair.first) {
         second_team_.erase(pair);
         return true;
       }
     }
   }
   return false;
 }
operator=()
Game& fusion_server::Game::operator= (const Game & other) delete noexcept
Explicitly deleted copy operator. It's deleted due to presence of unique_ptr in class hierarchy.
Parameters
[in] other Copied object.
Returns
Reference to this object.
Member Data Documentation
delegate_
system_abstractions::IncommingPackageDelegate fusion_server::Game::delegate_ private
This callable object is used as a callback to the asynchronous reading of all clients in this game.
Definition at line 262 of file game.hpp.
first_team_
std::set<std::pair<WebSocketSession*, std::unique_ptr<Player> > > fusion_server::Game::first_team_ private
This set contains the pairs of WebSocket sessions and their roles in the game of the first team.
Definition at line 208 of file game.hpp.
Referenced by DoResponse(), GetCurrentState(), and GetPlayersCount().
first_team_mtx_
std::mutex fusion_server::Game::first_team_mtx_ mutable private
This mutex is used to synchronise all oprations done on the collection containing the first team.
Definition at line 214 of file game.hpp.
Referenced by DoResponse(), GetCurrentState(), and GetPlayersCount().
kMaxPlayersPerTeam
constexpr size_t fusion_server::Game::kMaxPlayersPerTeam = 5 static
This constant contains the number of players that can be assigned to a team.
Definition at line 166 of file game.hpp.
next_player_id_
std::atomic<std::size_t> fusion_server::Game::next_player_id_ private
This is used to set the id of the next player. It holds the next free id.
Definition at line 244 of file game.hpp.
players_cache_mtx_
std::mutex fusion_server::Game::players_cache_mtx_ mutable private
This mutex is used to synchronise all oprations done on the map of WebSocket sessions and their players' team identifiers.
Definition at line 239 of file game.hpp.
Referenced by IsInGame().
rays_
std::map<std::variant<Ray*, Player*>, Ray> fusion_server::Game::rays_ private
This map contains all rays in the game. The key is the ray's parent which is either a player or another ray.
Definition at line 250 of file game.hpp.
Referenced by GetCurrentState().
rays_mtx_
std::mutex fusion_server::Game::rays_mtx_ mutable private
This mutex is used to synchronise all oprations done on the map containing the rays.
Definition at line 256 of file game.hpp.
Referenced by GetCurrentState().
second_team_
std::set<std::pair<WebSocketSession*, std::unique_ptr<Player> > > fusion_server::Game::second_team_ private
This set contains the pairs of WebSocket sessions and their roles in the game of the second team.
Definition at line 220 of file game.hpp.
Referenced by DoResponse(), GetCurrentState(), and GetPlayersCount().
second_team_mtx_
std::mutex fusion_server::Game::second_team_mtx_ mutable private
This mutex is used to synchronise all oprations done on the collection containing the second team.
Definition at line 226 of file game.hpp.
Referenced by DoResponse(), GetCurrentState(), and GetPlayersCount().
The documentation for this class was generated from the following files:
include/fusion_server/game.hpp
src/game.cpp