Fusion Server: include/fusion_server/json.hpp File Reference
json.hpp File Reference
#include <optional>
#include <string>
#include <nlohmann/json.hpp>
Typedefs
using fusion_server::JSON = nlohmann::json
Functions
template<typename It1 , typename It2 >
std::optional< JSON > fusion_server::ParseJSON (It1 &&it1, It2 &&it2) noexcept
Parses the JSON object from given range.
std::pair< bool, JSON > fusion_server::VerifyJSON (const std::string &raw_package) noexcept
Detailed Description
This module is a part of Fusion Server project. It declares the JSON type and free functions used to parse from range types.
(c) 2019 by Kamil Rusin
Definition in file json.hpp.
Typedef Documentation
JSON
using fusion_server::JSON = typedef nlohmann::json
This is the JSON type used in the program.
Definition at line 22 of file json.hpp.
Function Documentation
ParseJSON()
template<typename It1 , typename It2 > std::optional<JSON> fusion_server::ParseJSON (It1 && it1, It2 && it2) noexcept
Parses the JSON object from given range.
Template Parameters
It1 An iterator type.
It2 An iterator type.
Parameters
[in] it1 An iterator of the beginning of the range.
[in] it2 An iterator of the end of the range.
Returns
If the operation was successful it returns a JSON object, otherwise it returns an "invalid-state" object.
Definition at line 44 of file json.hpp.
References fusion_server::ParseJSON(), and fusion_server::VerifyJSON().
Referenced by fusion_server::ParseJSON(), and fusion_server::VerifyJSON().
{
   try {
     return JSON::parse(std::forward<It1>(it1), std::forward<It2>(it2));
   }
   catch (...) {
     return {};
   }
 }
VerifyJSON()
std::pair< bool, JSON > fusion_server::VerifyJSON (const std::string & raw_package) noexcept
This function returns a pair of an indication whether or not the verification was successful and a JSON object which is either a parsed package or an error message.
Parameters
[in] raw_package The raw package read from a client.
Returns
A pair of an indication whether or not the verification was successful and a JSON object which is either a parsed package or an error message is returned.
Definition at line 105 of file json.cpp.
References fusion_server::ParseJSON(), and fusion_server::VerifyJSON().
Referenced by fusion_server::WebSocketSession::HandleRead(), fusion_server::ParseJSON(), and fusion_server::VerifyJSON().
{
   auto parsed = ParseJSON(raw_package.begin(), raw_package.end());
   if (!parsed) {
     return std::make_pair(false, MakeNotValidJSON());
   }
   auto json = std::move(parsed.value());
   if (!(json.contains("type") &&
         json["type"].type() == decltype(json)::value_t::string)) {
     return std::make_pair(false, MakeTypeNotFound());
   }
   if (json["type"] == "join") {
     if (!(json.contains("id") &&
           json.contains("nick") &&
           json.contains("game") &&
           json.size() ==  3 + 1 &&
           json["id"].type() == decltype(json)::value_t::number_unsigned &&
           json["nick"].type() == decltype(json)::value_t::string &&
           json["game"].type() == decltype(json)::value_t::string)) {
       return std::make_pair(false, MakeNotValidJoin());
     }
     return std::make_pair(true, std::move(json));
   }
   if (json["type"] == "update") {
     if (!(json.contains("team_id") &&
           json.contains("position") &&
           json.contains("angle") &&
           json.size() ==  3 + 1 &&
           json["team_id"].type() == decltype(json)::value_t::number_unsigned &&
           json["position"].type() == decltype(json)::value_t::array &&
           json["position"].size() == 2 &&
           json["position"][0].type() == decltype(json)::value_t::number_float &&
           json["position"][1].type() == decltype(json)::value_t::number_float &&
           json["angle"].type() == decltype(json)::value_t::number_float)) {
       return std::make_pair(false, MakeNotValidUpdate());
     }
     return std::make_pair(true, std::move(json));
   }
   if (json["type"] == "leave") {
     if (json.size() != 1) {
       return std::make_pair(false, MakeNotValidLeave());
     }
     return std::make_pair(true, std::move(json));
   }
   // Received an undefined package.
   return std::make_pair(false, MakeUnidentified());
 }