Fusion Server: executable/src/main.cpp File Reference
main.cpp File Reference
#include <cstring>
#include <chrono>
#include <functional>
#include <memory>
#include <thread>
#include <vector>
#include <boost/asio.hpp>
#include <spdlog/sinks/basic_file_sink.h>
#include <fusion_server/server.hpp>
#include <fusion_server/system_abstractions.hpp>
Functions
void HandleSignal (boost::asio::io_context &ioc, const boost::system::error_code &ec, int signal) noexcept
Asynchronous signal handler. This function used as the asynchronous signal handler.
void InitLogger () noexcept
Initialises loggers. This function initialises loggers for main modules of the program.
int main ()
The program's entry point. This function is the program's entry point. It creates the server instance, registers handled singnals and creates worker threads.
Detailed Description
This module is a part of Fusion Server project. It contains the implementation of main function.
(c) 2019 by Kamil Rusin
Definition in file main.cpp.
Function Documentation
HandleSignal()
void HandleSignal (boost::asio::io_context & ioc, const boost::system::error_code & ec, int signal) noexcept
Asynchronous signal handler. This function used as the asynchronous signal handler.
Parameters
ioc The I/O context used in the program.
ec The Boost's error code that incicates whether or not an error occured.
signal The signal code of the received signal.
Definition at line 37 of file main.cpp.
References fusion_server::Server::GetInstance(), and fusion_server::Server::Shutdown().
Referenced by main().
{
   if (ec) {
     spdlog::get("server")->error("An error occured during signal handling. [Boost: {}]",
       ec.message());
   }
   spdlog::get("server")->warn("Received a signal ({}). Stoping the I/O context.",
     strsignal(signal));
   ioc.stop();
   fusion_server::Server::GetInstance().Shutdown();
 }
main()
int main ()
The program's entry point. This function is the program's entry point. It creates the server instance, registers handled singnals and creates worker threads.
Returns
0 No error occured.
A error number.
Definition at line 78 of file main.cpp.
References fusion_server::Server::GetInstance(), HandleSignal(), and InitLogger().
            {
   InitLogger();
   auto& server = fusion_server::Server::GetInstance();
   if (!server.StartAccepting()) {
     return EXIT_FAILURE;
   }
   auto& ioc = server.GetIOContext();
   boost::asio::signal_set signals{ioc, SIGINT, SIGTERM};
   signals.async_wait(
     [&ioc] (const boost::system::error_code& ec, int signal) {
       HandleSignal(ioc, ec, signal);
     }
   );
   // TODO: read from config file
   auto number_of_workers = std::thread::hardware_concurrency() - 1;
   std::vector<std::thread> workers;
   workers.reserve(number_of_workers);
   for (std::size_t i = 0; i < number_of_workers; i++)
     workers.emplace_back([&ioc]{ ioc.run(); });
   spdlog::get("server")->info("Created {} threads.", number_of_workers);
   ioc.run();
   spdlog::get("server")->info("No more tasks. Waiting for threads to join.");
   for (auto& worker : workers) {
     auto id = worker.native_handle();
     worker.join();
     spdlog::get("server")->info("Worker {} has joined.", id);
   }
   return EXIT_SUCCESS;
 }